### PR TITLE
Add methods to client library

### PR DESCRIPTION
**Pull request by cgrigis**
Work in progress, do not pull yet.

### CODE REVIEW

**Comment by mar-v-in** [comment]
@cgrigis are you still working on this? Anything specific you need help with?

**Comment by cgrigis** [comment]
@mar-v-in Yes, sorry I was on holiday last week. I'll double-check that I have everything in today.

**Comment by cgrigis** [comment]
@mar-v-in Assuming the Travis checks pass, this should be ready now.
I am not yet quite clear on how `DiagnosisKeyFileProvider` is to be used, so the implementation of `provideDiagnosisKeys(DiagnosisKeyFileProvider provider)` might change, but I can update that when it's settled.

**Comment by mar-v-in** [comment]
Thanks!

**Pull request merged**
