### PR TITLE
Added IT lang files

### PR DESCRIPTION
**Pull request by Pdevo**
Not a real coder but a microG user that want to thank you for this project in its small way. I added translated strings for IT localization, hope there are not missing files or other things to be added, in that case, please, let me know.

Sorry for the inconvenience with the request, hope everything is fixed now.

### CODE REVIEW

**Comment by chris42** [comment]
@Pdevo You can actually keep a PR even if you need to do changes. Normally you create a PR branch in your repository. Every commit into that branch will automatically included into the PR here.

Thank you for contributing!

**Comment by Pdevo** [comment]
@chris42 Thank you for your suggestion, not so confident with github. Hope everything is fine now.

**Comment by chris42** [comment]
@Pdevo you can't break much. ;-D 

@mar-v-in will need to review the PR and merge it. I am not sure about his timeline and what is still on his list after he did the refactoring.

**Comment by ErnyTech** [comment]
In my opinion you should write the translation using a "more direct" form, for example substituting "Toccate qui" with "Tocca qui", "utilizzate" with "utilizza", "vostro dispositivo" with "tuo dispositivo".
A direct form makes the content clearer and I think it's better for a configuration screen.

**Comment by Pdevo** [comment]
@ErnyTech I generally think is better not to use such direct forms when the language allow to be more clean and polite (let's say also generic), at least this sounds better in italian language, but it is just a personal opinion ;) I can change that if you find it better

**Comment by Pdevo** [comment]
@ErnyTech ok, you got your point, I fixed that

**Comment by mar-v-in** [comment]
Thanks @Pdevo, this will make it in the next release. :smile:

**Pull request merged**
