### PR TITLE
Add patch for LineageOS

### PR DESCRIPTION
**Pull request by kylon**

### CODE REVIEW

**Comment by mar-v-in** [comment]
@kylon How is this patch different from the one we already have?

**Comment by Herny64** [comment]
i did a diff from the two patch files.
Hes using diff --ruN instead of diff --git.
Couldnt spot another differrence.

**Comment by kylon** [comment]
It does apply with no errors
The last time i used the N patch i had a build error.

@Henry64
Yea i had to manually apply the patch, so i used that command.

No changes to the patch itself, only the line numbers.

**Comment by kylon** [comment]
i just tried again a few minutes ago.
lineage does NOT build with your patch.

here are some lines (too many lines to copy all of them)

patch -p1 < microgpatch.patch

[makeerror.txt](https://github.com/microg/android_packages_apps_GmsCore/files/973585/makeerror.txt)

**Comment by iRave** [comment]
I just built LineageOS with the official patch. I had to reapply it because there where some changes in framework/base. When I did that, there were two warnings about line numbers that changed. 
It patched and build just fine though. Signature Spoofing does work as well after installing the new build.

**Comment by corna** [comment]
@kylon It's just because `patch` creates the `.orig` files in the same folder and the build system finds two sets of definitions, one in `strings.xml` and one in `strings.xml.orig`.

To fix it just run `git clean -f` (or `rm -f strings.xml.orig` to remove just the problematic file) in `frameworks/base` after applying the patch.

@mar-v-in This should be pointed out in the doc, as it applies to any ROM where the patch doesn't apply cleanly on `strings.xml`

**Comment by roblabla** [comment]
You're supposed to apply this patch with `git am` as far as I know. It builds completely fine on my system if you do this.

**Comment by Catfriend1** [comment]
What is needed to get this PR ready?

**Comment by kylon** [comment]
uh! still open

@Catfriend1 
see comments

**Pull request closed without merging**
