### PR TITLE
Allow to add a Google account and test location from microG settings (by @Vavun), ref: #719 #413

### PR DESCRIPTION
**Pull request by ale5000-git**
Allow to add a Google account and test location from microG settings (by @Vavun), ref: #719 #413

**Need testing.**

---
This change is [Reviewable](https://reviewable.io/reviews/microg/android_packages_apps_gmscore/727)

### CODE REVIEW

**Comment by Vavun** [comment]
Nice but I didnt test it at all.
It was a part of my old microg mod and I copypaste it only as example =)

**Comment by Nanolx** [comment]
I'm currently running a non-published build of my fork (`0.2.6.15180-dirty-194`) which contains this pull request and I can confirm it works as advertised.

Though maybe the geolocation part should be moved to uNlp, so that it is also available in the stand-alone version? Though, I don't know if that actually has a widespread user base (I _assume_ not). @mar-v-in ?

**Comment by ale5000-git** [comment]
Closed in favour of #735.

@Nanolx: Please re-test it if possible

**Comment by ale5000-git** [comment]
@Nanolx: For the "geolocation part should be moved to uNlp" it is a good idea but since the PR #735 is already ready I think it is better to do the change in a separate PR.

**Pull request closed without merging**
