### PR TITLE
new submodule: Phonesky patches for microG (in-)app-purchases support

### PR DESCRIPTION
**Pull request by Nanolx**
For a long while now I've been creating patches to Phonesky (and a self-signed apk build) which allows for (in-)app-purchases with microG on all ROMs. While there are Stock ROMs which don't need a patched Play Store, basically all AOSP/LOS based custom ROMs do.

Details on the reason why and the proposed solution here have already been discussed in #309 

This commits adds the Phonesky patches repository (I just created) as a new submodule.

Instructions are pretty straight-forward:

- download Phonesky from apkmirror (or the-like)
- `java -jar apktool.jar d <phonesky.apk>`
- `cd <phonesky>`
- `find . -type f -name '*.xml' | xargs sed '/APKTOOL_DUMMY/d' -i`
- `patch -Np1 -i <phonesky.diff>`
- `java -jar apktool.jar b <phonesky>`
- sign `<phonesky>/dist/<phonesky.apk>`

et voilá.

Initial Phonesky installations needs to be in `/system/priv-app`, required permission files are inside `etc/`.

I'm open for suggestions. If desired I can also add all older patches I've created to the repo, aswell.

### CODE REVIEW

**Comment by Nanolx** [comment]
for reference the patch history can be found here: https://gitlab.com/Nanolx/NanoDroid/commits/master/doc/Phonesky.diff

**Comment by ArchangeGabriel** [comment]
(JFYI: it’s « et voilà » with an à, not an á ;p)

**Comment by Nanolx** [comment]
I just uploaded all 'historical' patches aswell and added a README with instructions.

**Comment by lucassz** [comment]
I had to add the following lines to `com.android.vending.xml` to get this to load on Lineage for MicroG:

`<permission name="android.permission.READ_PRIVILEGED_PHONE_STATE"/>
<permission name="android.permission.REBOOT"/>`

**Comment by Nanolx** [comment]
While this is not related to this pull request and should have been posted over at the gitlab repo... that's likely, as different Android versions and sometimes even flavors expect different privapp-permission whitelists.

I'm currently working on extending my Installer to auto-create the files. See this commit https://gitlab.com/Nanolx/NanoDroid/commit/6f53d0af20b0e87fbcae5fbb80f76c959c502d2b 

The functions are not yet in use and no aapt binaries are (yet) included by NanoDroid.

cc'ing @ale5000-git in case you're interested in this.

**Comment by Nanolx** [comment]
@ale5000-git the code is now in place and seem to create proper privapp-permission whitelist files.

**Comment by ale5000-git** [comment]
@Nanolx: Thanks, currently I'm busy but I will look as soon I can.

**Comment by Nanolx** [comment]
@mar-v-in given you want to get rid of sub modules this is kinda redundant now, no? Is there any interest to get the patches into the project?

@ale5000-git one fix to the affore mentioned auto-privapp-whitelisting function: https://gitlab.com/Nanolx/NanoDroid/commit/e1fb9fb49f2e0b34a94ddd9e9d04d4eec332873d

**Comment by Nanolx** [comment]
I catched up with Play Store releases up to 16.9.10. But more importantly I've written a basic script which automates the patching process. Feel free to give it a try.

https://gitlab.com/Nanolx/microg-phonesky-iap-support/blob/master/patch-playstore

**Comment by Nanolx** [comment]
Slightly improved the `patch-playstore` script.

**Comment by Nanolx** [comment]
keeping this updated, just in case there's any interest:

- improved `patch-playstore` script
- improved documentation
- improved Installer code for auto-detecting required privapp-permissions to be whitelisted (https://gitlab.com/Nanolx/NanoDroid/blob/master/CommonInstaller#L865)
   - will be broken-out into a script useable on-pc later on

**Comment by Nanolx** [comment]
Since I've got no response I assume there's no interest in it, so I'm closing this now.

**Comment by mar-v-in** [comment]
@Nanolx I don't think Phonesky patches belong in the GmsCore repo. And we finally got rid of submodules for everything ;)

**Pull request closed without merging**
