### PR TITLE
Allow Google Pay India

### PR DESCRIPTION
**Pull request by yeshwanthvshenoy**
Adding Google Pay India version signature to known apps.

Relevant Logs:

```
06-25 00:32:21.215  8788  8806 D GmsServicesProvider: query caller=com.google.android.apps.nbu.paisa.user name=primes:shutdown_primes value=null
06-25 00:32:21.243  8788  8788 D GmsClearcutSvc: onBind: Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms }
06-25 00:32:21.295  8788  9116 D GmsAuthProvider: Call from com.google.android.apps.nbu.paisa.user
06-25 00:32:21.298  8788  9116 W GmsAuthProvider: Not granting extended access to [com.google.android.apps.nbu.paisa.user], signature: 80df78bb700f9172bc671779b017ddefefcbf552
06-25 00:32:21.299  8788  9116 E DatabaseUtils: Writing exception to parcel
06-25 00:32:21.299  8788  9116 E DatabaseUtils: java.lang.SecurityException: Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission
06-25 00:32:21.299  8788  9116 E DatabaseUtils: 	at org.microg.gms.auth.AccountContentProvider.call(Unknown Source:134)
06-25 00:32:21.299  8788  9116 E DatabaseUtils: 	at android.content.ContentProvider.call(ContentProvider.java:2152)
06-25 00:32:21.299  8788  9116 E DatabaseUtils: 	at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
06-25 00:32:21.299  8788  9116 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
06-25 00:32:21.299  8788  9116 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1021)
06-25 00:32:21.299  8788  9116 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:994)
```

### CODE REVIEW

**Comment by yeshwanthvshenoy** [comment]
@mar-v-in please review and add in next release. Indian folks need this badly!

**Comment by p00f** [comment]
Does registration work? I get "Oops something went wrong!" when I submit my phone number and wait for the OTP

**Comment by p00f** [comment]
Screenshot_20210607-203350

**Comment by yeshwanthvshenoy** [comment]
@p00f It used to work back in Aug. Not sure now. I have moved out of MicroG system now. You can check the apk signature though if they are the same. Also check adb logs to get better idea.

**Pull request merged**
