### PR TITLE
Çekme

### PR DESCRIPTION
**Pull request by alperates112**
Çek

### CODE REVIEW

**Comment by chris42** [comment]
Can anyone elaborate on what this PR is good for?

**Comment by ArchangeGabriel** [comment]
It seems to be merging VancedMicroG into MicroG, which is a non-sense. Also, this GitHub user was created just before this PR. I would just close it.

**Comment by chris42** [comment]
I never followed Vanced microg so have no clue if there were any helpful developments over there. If so it would probably make sense to PR each fix/enhancement on its own, other than this unloading of commits.

@alperates112 If you are just updating your Vanced microg fork with the latest changes in original microg, you are doing it the wrong way around...

**Comment by Oizaro** [comment]
@alperates112 Please...can you just avoid to do these mistakes without fixing it?

P.S: And no...don't rename this PR with the suggestion "don't pull". Just close it instead xD.

**Comment by Oizaro** [comment]
@chris42 He just fork our repo for his use, but he clicked the pull request button by mistake and got into trouble. Plus he's not an user of our server, so we can't contact him in cases like this.

**Pull request closed without merging**
