### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by Gena95**
Translated new strings and minor translation fixes.

### CODE REVIEW

**Comment by mar-v-in** [comment]
I just updated the pref_snet_status_official_summary string, see https://github.com/microg/android_packages_apps_GmsCore/commit/32d6040e551cc0711273694d499ef6ea21594466#diff-a053a7795f677d520136b0d3d4eae36a . Can you please update your translation as well? Thanks.

**Comment by Gena95** [comment]
Updated!
Where I can find strings in GCM per app setting such as "Start the app in background to receive the incoming push messages".

**Comment by mar-v-in** [comment]
The GCM advanced strings are not yet translatable, will do this in a few days.

**Comment by Gena95** [comment]
Well, thank you, I will wait :)

**Pull request merged**
