### PR TITLE
improve microG settings (fix issue #758 and more)

### PR DESCRIPTION
**Pull request by Nanolx**
Follow up commit to #719 and #741 includes:

- separates launcher icon from main activity (so it can be disabled without making microG inaccessible, think of Launchers that don't allow to hide Apps on their own)
- fix issue #758 (launcher icon not shown on all devices)
- #741 added 'Add account' to microG Settings, this here adds the 'Trust Google for app permissions' checkbox aswell (new 'Account' settings group)
- #719 added 'microG settings' to System Settings > Device, move into System Settings directly (result may vary, depending on the ROM and Android Release)
- improved version of the microG icon for System Settings
- made several GCM related strings translatable
- updated russian translation
- updated german translation

### CODE REVIEW

**Comment by Nanolx** [comment]
- updated ukrainian translation

**Comment by Nanolx** [comment]
- added new pref to 'Account' settings category introduced by 30ed2720a0ecd3067fe760e801ecbdbe1b5ff5be

**Comment by mar-v-in** [comment]
Can you change the class/xml name of the account settings to not be "add account"? It's a little confusing ;)

Thanks.

**Comment by mar-v-in** [comment]
Also you are lacking the logic code required for the `auth_manager_visible` preferences to be applied directly (as implemented in the `AccountSettingsActivity`)

**Comment by Nanolx** [comment]
Yes, of course, completely missed it out. Will fix it later today.

Am 29. Mai 2019 17:19:47 MESZ schrieb Marvin W <notifications@github.com>:
>Also you are lacking the logic code required for the
>`auth_manager_visible` preferences to be applied directly (as
>implemented in the `AccountSettingsActivity`)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/pull/765#issuecomment-496982776

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Vavun** [comment]
Hi @mar-v-in !

What do you think about simplify string "Google Cloud Messaging" to "Cloud Messaging" or something else ?

Because GCM is not exist anymore

**Comment by Nanolx** [comment]
If there's anything left you'd like to see changed, just let me know.

**Comment by oldosfan** [comment]
How about using this Android 9 compliant settings menu? The current icon looks sort of wrong with Pie.

```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item>
        <shape android:shape="oval">
            <solid
                android:color="#C2185B" />
            <size
                android:width="36dp"
                android:height="36dp" />
        </shape>
    </item>

    <item
        android:width="24dp"
        android:height="24dp"
        android:gravity="center" >
        <vector xmlns:android="http://schemas.android.com/apk/res/android"
            android:width="24dp"
            android:height="24dp"
            android:viewportWidth="24"
            android:viewportHeight="24">
            <path
                android:fillColor="#ffffffff"
                android:pathData="M14.5335,0.0569535 L9.43985,0.0705542 C9.24288,0.102156,9.0985,0.18001,9.06273,0.352909 L8.55771,3.75569 C7.70454,4.01856,7.0852,4.47885,6.46902,4.94163 L3.48987,3.74936 C3.23326,3.67936,2.95937,3.47486,2.64004,3.95331 L0.0871706,8.21668 C0.0372893,8.41036,0.0580599,8.56989,0.145272,8.69686 L2.93012,10.8425 C2.83047,11.6279,2.86713,12.4355,2.90092,13.2426 L0.23227,15.219 C0.005066,15.4246,0.050044,15.7049,0.087127,15.8119 L2.78493,20.2165 C2.89848,20.3411,3.04458,20.3919,3.22668,20.3608 L6.49813,19.1434 C7.12487,19.6363,7.79275,20.0492,8.52873,20.3294 L8.99269,23.3505 C9.11365,23.56,9.09564,23.8073,9.4858,23.9434 L14.6784,23.9434 C14.8701,23.8649,15.0801,23.8217,15.1137,23.4353 L15.5776,20.2729 C16.4832,19.9372,17.01,19.5277,17.6663,19.1435 L20.7121,20.3576 C21.1885,20.4803,21.2695,20.2522,21.3504,20.16 L23.8741,15.8401 C23.9395,15.7104,23.9625,15.4495,23.787,15.2191 L21.1762,13.2708 C21.1953,12.4738,21.2347,11.6899,21.1762,10.8426 L23.874,8.72511 C23.996,8.49886,23.9302,8.24834,23.874,8.10387 L21.3214,3.92514 C21.1924,3.70382,20.9206,3.64557,20.7701,3.67097 L17.6082,4.94163 C16.8967,4.38465,16.2039,3.98905,15.5197,3.67097 L14.9974,0.395711 C14.9027,0.136848,14.7173,0.0991057,14.5334,0.0570135 Z M11.8718,5.62811 C13.7255,5.60431,15.517,6.32771,16.5932,7.54186 L14.7953,9.4995 C13.2639,8.11395,9.57199,7.53593,8.30443,11.1012 C7.82376,12.9227,8.54727,14.4138,10.0518,15.2852 C11.6506,16.1862,14.0977,15.4204,14.7343,14.7492 L16.6846,16.6771 C15.8496,17.3442,12.7132,19.81,8.67011,17.6858 C6.61824,16.5517,4.69843,14.6267,5.53146,10.4485 C6.00671,8.8177,7.06262,7.50059,8.60931,6.53345 C9.62512,5.92563,10.7596,5.64239,11.8718,5.62811 Z" />
        </vector>
    </item>
</layer-list>
```

**Comment by Nanolx** [comment]
@oldosfan what ROM are you using? For me it looks normal on Pie (both in Launcher and System Settings), maybe post a screenshot.

@mar-v-in is there anything left you'd like to see changed/improved?

**Comment by Nanolx** [comment]
@mar-v-in any interest in the parts which can be rebased on latest code?

**Comment by mar-v-in** [comment]
- Launcher activity alias: probably makes sense if some users have issues with that
- Accounts settings: I planed to have a completely new screen with all accounts listed, ability to add accounts and all the account settings and a new option to disable the whole account management, so that everything is in one place. So this change is probably going to be replaced with something else soon anyway
- Add to system settings: Has to be taken with care that it doesn't break any existing microG integrations (like /e/)
- Translations: Probably doesn't hurt
- Updated icon: Updating the icon to something that's more compliant with current android icon guidelines is on my todo anyway, but I'd have to check if this one fulfills my expectation. If it's the one that I remember, then I didn't really liked it.

**Comment by Nanolx** [comment]
see 1191 for replacement.

**Pull request closed without merging**
