### PR TITLE
Add version check to skip first screen on KK (login fix)

### PR DESCRIPTION
**Pull request by Nanolx**
Fixes for the login screen issue ("Login" button not clickable) by @PorygonZRocks - reportedly works.

(I know it's not common for a thirdparty to send in a pull request, but still)

### CODE REVIEW

**Comment by PorygonZRocks** [comment]
Afaik this never got tested, so I *think* it should work but am not sure. I see you said it "reportedly works" so I assume someone did end up testing it?

**Comment by Nanolx** [comment]
It's part of my custom microG build (included along side the official one in my NanoDroid project) and two or three (known) KK users stopped their login-complains and reported "everything works now".

I don't have a KK device on my own, so I relying on user feedback for this one.

**Comment by Vavun** [comment]
> 
> 
> Afaik this never got tested, so I _think_ it should work but am not sure. I see you said it "reportedly works" so I assume someone did end up testing it?

I can confirm that it works without problems. 
10+ people on russian community confirmed that microg fork with this fix solved their login problem on kitcat or lower and no one reported problems with login issues on KK after that. (1000+ fork downloads)

**Comment by voidstarstar** [comment]
Fixes #491 and fixes #368.  These were not linked from this PR, so they need to be manually closed once verified.

**Pull request merged**
