### PR TITLE
Add account button and location picker button to microG settings, supersede #727, fix #413

### LINKED ISSUE #413: Can't add google account on alternative android implementation.
I'm using a Jolla C ( https://jolla.com ) which uses aliendalvik ( http://www.myriadgroup.com/en/products/device-solutions/mobile-software/alien-dalvik/ ). On top of that I installed microg as described here: https://www.joachim-breitner.de/blog/713-microG_on_Jolla

This combinations works just fine except for one issue: I have an app which requires a google account linked to the play services. Now I read that this should be doable from android settings but the Jolla / aliendalvik is missing said setting. That said I think it would be great if microg would offer a way to add an account in its own settings.

//EDIT: Forgot to say: In the past I used the original Google Play Services on the same phone and they offered a way to add an account. Anyway, I don't want to use them anymore so I hope this feature request will make it. :)

### PR DESCRIPTION
**Pull request by ale5000-git**
Add account button and location picker button to microG settings, supersede #727, fix #413

@Vavun

---
This change is [Reviewable](https://reviewable.io/reviews/microg/android_packages_apps_gmscore/735)

### CODE REVIEW

**Comment by Nanolx** [comment]
working fine here; updated german translation accordingly, feel free to merge/cherry-pick: https://github.com/Nanolx/android_packages_apps_GmsCore/commit/4f316e68b1874fa0c83363eb1162f98116c8ab46

**Comment by ale5000-git** [comment]
@mar-v-in: This PR is ready.

Can you please merge it?

**Comment by Vavun** [comment]
@ale5000-git you should not be in such a hurry.
@Nanolx is working on better variant

**Comment by Nanolx** [comment]
@vavun Technically you're working on it and I'm just mentoring/testing it. :)

I'll create a new branch with those changes isolated, the next days.

**Comment by ale5000-git** [comment]
I have created the #741 for the account thing, I will left the rest to you.

**Pull request closed without merging**
